-- =============================================================================
-- 상품 필터(facet) Phase 2b — Tier 2(카테고리 전용) 정의 + 카테고리 매핑
-- 설계: docs/사이트개선/카테고리_브랜드_상품필터_설계.md §4
--
-- ⚠ 설계 대비 정리한 점 — "품목/종류" 축은 facet 으로 만들지 않는다.
--   §4 초안의 ITEM_TYPE · COSMETIC_TYPE · DEVICE_TYPE · FURNITURE_TYPE · BABY_ITEM
--   · FOOD_TYPE · SPORT_TYPE · BOOK_GENRE · SERVICE_TYPE · CLOTH_TYPE 은 전부
--   "2뎁스(또는 3뎁스) 카테고리 파생" 이라 Tier 0 CATEGORY 필터와 값이 같다.
--   같은 것을 두 벌 관리하면 반드시 어긋나므로 CATEGORY 하나로 통합했다.
--   → 필터 개수 약 90 → 60.
--
-- 카테고리는 이름으로 매칭한다(ID 하드코딩 금지).
-- 새로 찍어낸 몰에도 같은 이름의 1뎁스가 있으면 그대로 적용된다.
--
-- 멱등하다. 적용: mysql ... yd_mall < 20260722_facet_phase2b_category.sql
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Tier 2 필터 정의
-- -----------------------------------------------------------------------------
INSERT INTO facet_definition
    (facet_code, facet_name, tier, ui_type, value_source, source_key, data_type, unit, is_multi, is_active, display_order, meta_json)
VALUES
-- 패션의류
('FIT','핏',2,'CHIP','ATTRIBUTE','FIT','STRING',NULL,1,1,210,NULL),
('SLEEVE','소매·기장',2,'CHIP','ATTRIBUTE','SLEEVE','STRING',NULL,1,1,211,NULL),
('PATTERN','패턴',2,'CHECKBOX','ATTRIBUTE','PATTERN','STRING',NULL,1,1,212,NULL),
('WASH','세탁 방법',2,'CHIP','ATTRIBUTE','WASH','STRING',NULL,1,1,213,NULL),
-- 패션잡화
('HEEL_HEIGHT','굽 높이',2,'CHIP','ATTRIBUTE','HEEL_HEIGHT','STRING',NULL,1,1,220,NULL),
('LUGGAGE_INCH','캐리어 인치',2,'CHIP','ATTRIBUTE','LUGGAGE_INCH','NUMBER','인치',1,1,221,NULL),
('PURITY','순도',2,'CHIP','ATTRIBUTE','PURITY','STRING',NULL,1,1,222,NULL),
('WEIGHT_G','중량',2,'CHECKBOX','ATTRIBUTE','WEIGHT_G','RANGE','g',1,1,223,NULL),
('WARRANTY_CARD','보증서',2,'TOGGLE','ATTRIBUTE','WARRANTY_CARD','BOOL',NULL,0,1,224,NULL),
('BAND_MATERIAL','밴드 재질',2,'CHECKBOX','ATTRIBUTE','BAND_MATERIAL','STRING',NULL,1,1,225,NULL),
-- 화장품/미용
('SKIN_TYPE','피부 타입',2,'CHECKBOX','ATTRIBUTE','SKIN_TYPE','STRING',NULL,1,1,230,NULL),
('FUNCTION','기능성',2,'CHECKBOX','ATTRIBUTE','FUNCTION','STRING',NULL,1,1,231,NULL),
('CONCERN','피부 고민',2,'CHECKBOX','ATTRIBUTE','CONCERN','STRING',NULL,1,1,232,NULL),
('FORM','제형',2,'CHECKBOX','ATTRIBUTE','FORM','STRING',NULL,1,1,233,NULL),
('SPF','자외선 차단 지수',2,'CHIP','ATTRIBUTE','SPF','STRING',NULL,1,1,234,NULL),
('INGREDIENT_FREE','성분 특징',2,'CHECKBOX','ATTRIBUTE','INGREDIENT_FREE','STRING',NULL,1,1,235,NULL),
('SCENT','향 계열',2,'CHECKBOX','ATTRIBUTE','SCENT','STRING',NULL,1,1,236,NULL),
('SHADE','색상·호수',2,'CHIP','ATTRIBUTE','SHADE','STRING',NULL,1,1,237,NULL),
-- 디지털/가전
('MAKER','제조사',2,'CHECKBOX','ATTRIBUTE','MAKER','STRING',NULL,1,1,240,JSON_OBJECT('searchable',true,'collapseAfter',8)),
('ENERGY_GRADE','에너지소비효율등급',2,'CHIP','ATTRIBUTE','ENERGY_GRADE','STRING',NULL,1,1,241,NULL),
('RELEASE_YEAR','출시연도',2,'CHIP','ATTRIBUTE','RELEASE_YEAR','NUMBER','년',1,1,242,NULL),
('SCREEN_INCH','화면 크기',2,'CHECKBOX','ATTRIBUTE','SCREEN_INCH','RANGE','인치',1,1,243,NULL),
('FORM_FACTOR','형태',2,'CHECKBOX','ATTRIBUTE','FORM_FACTOR','STRING',NULL,1,1,244,NULL),
('POWER_W','소비전력',2,'CHECKBOX','ATTRIBUTE','POWER_W','RANGE','W',1,1,245,NULL),
('VOLTAGE','정격전압',2,'CHIP','ATTRIBUTE','VOLTAGE','STRING',NULL,1,1,246,NULL),
('STORAGE','저장 용량',2,'CHIP','ATTRIBUTE','STORAGE','STRING',NULL,1,1,247,NULL),
('OS','운영체제',2,'CHIP','ATTRIBUTE','OS','STRING',NULL,1,1,248,NULL),
('CONNECTIVITY','연결 방식',2,'CHECKBOX','ATTRIBUTE','CONNECTIVITY','STRING',NULL,1,1,249,NULL),
('INSTALL_FEE','설치 비용',2,'CHIP','ATTRIBUTE','INSTALL_FEE','STRING',NULL,1,1,250,NULL),
('CARRIER','이동통신사',2,'CHIP','ATTRIBUTE','CARRIER','STRING',NULL,1,1,251,NULL),
('WARRANTY','보증 기간',2,'CHIP','ATTRIBUTE','WARRANTY','STRING',NULL,1,1,252,NULL),
-- 가구/인테리어
('SEATS','인원·수용',2,'CHIP','ATTRIBUTE','SEATS','STRING',NULL,1,1,260,NULL),
('WIDTH_CM','폭(가로)',2,'CHECKBOX','ATTRIBUTE','WIDTH_CM','RANGE','mm',1,1,261,NULL),
('ASSEMBLY','조립 방식',2,'CHIP','ATTRIBUTE','ASSEMBLY','STRING',NULL,1,1,262,NULL),
('STYLE','스타일',2,'CHECKBOX','ATTRIBUTE','STYLE','STRING',NULL,1,1,263,NULL),
('SET_COMPOSITION','구성',2,'CHIP','ATTRIBUTE','SET_COMPOSITION','STRING',NULL,1,1,264,NULL),
-- 출산/육아
('AGE_RANGE','사용 연령',2,'CHIP','ATTRIBUTE','AGE_RANGE','STRING',NULL,1,1,270,NULL),
('BABY_GENDER','성별',2,'CHIP','ATTRIBUTE','BABY_GENDER','STRING',NULL,1,1,271,NULL),
('DIAPER_STAGE','기저귀 단계',2,'CHIP','ATTRIBUTE','DIAPER_STAGE','STRING',NULL,1,1,272,NULL),
('DIAPER_TYPE','기저귀 형태',2,'CHIP','ATTRIBUTE','DIAPER_TYPE','STRING',NULL,1,1,273,NULL),
('FORMULA_STAGE','분유·이유식 단계',2,'CHIP','ATTRIBUTE','FORMULA_STAGE','STRING',NULL,1,1,274,NULL),
('WEIGHT_LIMIT','체중 한계',2,'CHIP','ATTRIBUTE','WEIGHT_LIMIT','RANGE','kg',1,1,275,NULL),
('SAFETY_MARK','안전 표시',2,'TOGGLE','ATTRIBUTE','SAFETY_MARK','BOOL',NULL,0,1,276,NULL),
('ECO_CERT','친환경',2,'CHECKBOX','ATTRIBUTE','ECO_CERT','STRING',NULL,1,1,277,NULL),
-- 식품
('STORAGE_TEMP','보관 방법',2,'CHIP','ATTRIBUTE','STORAGE_TEMP','STRING',NULL,1,1,280,NULL),
('WEIGHT_RANGE','중량·용량',2,'CHECKBOX','ATTRIBUTE','WEIGHT_RANGE','RANGE','g',1,1,281,NULL),
('HEALTH_FUNC','건강 기능',2,'CHECKBOX','ATTRIBUTE','HEALTH_FUNC','STRING',NULL,1,1,282,NULL),
('HFF_CERT','건강기능식품',2,'TOGGLE','ATTRIBUTE','HFF_CERT','BOOL',NULL,0,1,283,NULL),
('FOOD_CERT','인증',2,'CHECKBOX','ATTRIBUTE','FOOD_CERT','STRING',NULL,1,1,284,NULL),
('ALLERGY_FREE','알레르기',2,'CHECKBOX','ATTRIBUTE','ALLERGY_FREE','STRING',NULL,1,1,285,NULL),
('NUTRITION','영양 특징',2,'CHECKBOX','ATTRIBUTE','NUTRITION','STRING',NULL,1,1,286,NULL),
('FLAVOR','맛',2,'CHECKBOX','ATTRIBUTE','FLAVOR','STRING',NULL,1,1,287,NULL),
('COOK_TYPE','조리 형태',2,'CHIP','ATTRIBUTE','COOK_TYPE','STRING',NULL,1,1,288,NULL),
('GMO','유전자변형',2,'TOGGLE','ATTRIBUTE','GMO','BOOL',NULL,0,1,289,NULL),
('EXPIRY_SOON','유통기한',2,'CHIP','DERIVED',NULL,'STRING',NULL,1,1,290,NULL),
-- 스포츠/레저
('GEAR_TYPE','용품 유형',2,'CHIP','ATTRIBUTE','GEAR_TYPE','STRING',NULL,1,1,300,NULL),
('SKILL_LEVEL','숙련도',2,'CHIP','ATTRIBUTE','SKILL_LEVEL','STRING',NULL,1,1,301,NULL),
('USE_ENV','사용 환경',2,'CHIP','ATTRIBUTE','USE_ENV','STRING',NULL,1,1,302,NULL),
('CAPACITY_PERSON','사용 인원',2,'CHIP','ATTRIBUTE','CAPACITY_PERSON','STRING',NULL,1,1,303,NULL),
-- 여가/생활편의 (서비스 상품)
('REGION','지역',2,'CHECKBOX','ATTRIBUTE','REGION','STRING',NULL,1,1,310,NULL),
('DURATION','이용 기간',2,'CHIP','ATTRIBUTE','DURATION','STRING',NULL,1,1,311,NULL),
('USE_METHOD','이용 방식',2,'CHIP','ATTRIBUTE','USE_METHOD','STRING',NULL,1,1,312,NULL),
('HEADCOUNT','인원',2,'CHIP','ATTRIBUTE','HEADCOUNT','STRING',NULL,1,1,313,NULL),
('VALID_UNTIL','유효 기간',2,'CHIP','ATTRIBUTE','VALID_UNTIL','STRING',NULL,1,1,314,NULL),
('REFUND','환불 조건',2,'CHIP','ATTRIBUTE','REFUND','STRING',NULL,1,1,315,NULL),
('RESERVE','예약',2,'TOGGLE','ATTRIBUTE','RESERVE','BOOL',NULL,0,1,316,NULL),
-- 도서
('AUTHOR','저자',2,'CHECKBOX','ATTRIBUTE','AUTHOR','STRING',NULL,1,1,320,JSON_OBJECT('searchable',true,'collapseAfter',8)),
('PUBLISHER','출판사',2,'CHECKBOX','ATTRIBUTE','PUBLISHER','STRING',NULL,1,1,321,JSON_OBJECT('searchable',true,'collapseAfter',8)),
('PUBLISH_YEAR','출간 시기',2,'CHIP','ATTRIBUTE','PUBLISH_YEAR','STRING',NULL,1,1,322,NULL),
('BOOK_FORM','형태',2,'CHIP','ATTRIBUTE','BOOK_FORM','STRING',NULL,1,1,323,NULL),
('BOOK_CONDITION','도서 상태',2,'CHIP','ATTRIBUTE','BOOK_CONDITION','STRING',NULL,1,1,324,NULL),
('LANGUAGE','언어',2,'CHIP','ATTRIBUTE','LANGUAGE','STRING',NULL,1,1,325,NULL),
('TARGET_AGE','대상 연령',2,'CHIP','ATTRIBUTE','TARGET_AGE','STRING',NULL,1,1,326,NULL),
('PAGES','쪽수',2,'CHECKBOX','ATTRIBUTE','PAGES','RANGE','쪽',1,1,327,NULL),
('BOOK_SIZE','판형',2,'CHIP','ATTRIBUTE','BOOK_SIZE','STRING',NULL,1,1,328,NULL)
ON DUPLICATE KEY UPDATE
    facet_name = VALUES(facet_name), tier = VALUES(tier), ui_type = VALUES(ui_type),
    value_source = VALUES(value_source), source_key = VALUES(source_key),
    data_type = VALUES(data_type), unit = VALUES(unit), is_multi = VALUES(is_multi),
    is_active = VALUES(is_active), display_order = VALUES(display_order), meta_json = VALUES(meta_json);


-- -----------------------------------------------------------------------------
-- 2. Tier 2 값
-- -----------------------------------------------------------------------------
INSERT INTO facet_value_definition (facet_id, value_code, display_name, display_order, meta_json) VALUES
-- 패션의류
((SELECT id FROM facet_definition WHERE facet_code='FIT'),'SLIM','슬림',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FIT'),'REGULAR','레귤러',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FIT'),'OVER','오버핏',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FIT'),'WIDE','와이드',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'SLEEVELESS','민소매',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'SHORT','반팔',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'SEVEN','7부',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'LONG','긴팔',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'CROP','크롭',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'MIDI','미디',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SLEEVE'),'MAXI','롱',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'SOLID','무지',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'STRIPE','스트라이프',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'CHECK','체크',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'FLOWER','플라워',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'DOT','도트',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PATTERN'),'GRAPHIC','그래픽',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WASH'),'WATER','물세탁',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WASH'),'DRY','드라이 전용',20,NULL),
-- 패션잡화
((SELECT id FROM facet_definition WHERE facet_code='HEEL_HEIGHT'),'FLAT','플랫(1cm 이하)',10,JSON_OBJECT('min',0,'max',1)),
((SELECT id FROM facet_definition WHERE facet_code='HEEL_HEIGHT'),'LOW','로우(1~3cm)',20,JSON_OBJECT('min',1,'max',3)),
((SELECT id FROM facet_definition WHERE facet_code='HEEL_HEIGHT'),'MID','미들(3~7cm)',30,JSON_OBJECT('min',3,'max',7)),
((SELECT id FROM facet_definition WHERE facet_code='HEEL_HEIGHT'),'HIGH','하이(7cm 이상)',40,JSON_OBJECT('min',7,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='LUGGAGE_INCH'),'14','14인치',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LUGGAGE_INCH'),'20','20인치',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LUGGAGE_INCH'),'24','24인치',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LUGGAGE_INCH'),'28','28인치',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PURITY'),'14K','14K',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PURITY'),'18K','18K',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PURITY'),'24K','24K',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PURITY'),'925','925 실버',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_G'),'W1','1g 이하',10,JSON_OBJECT('min',0,'max',1)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_G'),'W3','1~3g',20,JSON_OBJECT('min',1,'max',3)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_G'),'W5','3~5g',30,JSON_OBJECT('min',3,'max',5)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_G'),'W5P','5g 이상',40,JSON_OBJECT('min',5,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='WARRANTY_CARD'),'Y','보증서 제공',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BAND_MATERIAL'),'METAL','메탈',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BAND_MATERIAL'),'LEATHER','가죽',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BAND_MATERIAL'),'URETHANE','우레탄',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BAND_MATERIAL'),'FABRIC','패브릭',40,NULL),
-- 화장품/미용
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'DRY','건성',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'OILY','지성',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'COMBO','복합성',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'SENSITIVE','민감성',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'TROUBLE','트러블성',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKIN_TYPE'),'ALL','모든 피부',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FUNCTION'),'WHITENING','미백',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FUNCTION'),'WRINKLE','주름개선',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FUNCTION'),'UV','자외선차단',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FUNCTION'),'TRIPLE','3중 기능성',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'MOISTURE','보습',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'SOOTHING','진정',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'PORE','모공',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'EXFOLIATE','각질',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'ELASTICITY','탄력',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'TROUBLE','트러블',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONCERN'),'ANTIAGING','안티에이징',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'CREAM','크림',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'LOTION','로션',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'SERUM','에센스·세럼',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'AMPOULE','앰플',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'OIL','오일',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'GEL','젤',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'MIST','미스트',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'BALM','밤',80,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'STICK','스틱',90,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM'),'PAD','패드',100,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SPF'),'UNDER30','SPF30 미만',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SPF'),'SPF30','SPF30~49',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SPF'),'SPF50','SPF50+',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INGREDIENT_FREE'),'NO_FRAGRANCE','무향료',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INGREDIENT_FREE'),'NO_PARABEN','무파라벤',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INGREDIENT_FREE'),'NO_ALCOHOL','무알코올',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INGREDIENT_FREE'),'VEGAN','비건',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INGREDIENT_FREE'),'LOW_IRRITANT','저자극',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCENT'),'NONE','무향',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCENT'),'FLORAL','플로럴',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCENT'),'CITRUS','시트러스',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCENT'),'WOODY','우디',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCENT'),'MUSK','머스크',50,NULL),
-- 디지털/가전
((SELECT id FROM facet_definition WHERE facet_code='ENERGY_GRADE'),'1','1등급',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ENERGY_GRADE'),'2','2등급',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ENERGY_GRADE'),'3','3등급',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ENERGY_GRADE'),'4','4등급',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ENERGY_GRADE'),'5','5등급',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SCREEN_INCH'),'S32','32인치 이하',10,JSON_OBJECT('min',0,'max',32)),
((SELECT id FROM facet_definition WHERE facet_code='SCREEN_INCH'),'S49','32~49인치',20,JSON_OBJECT('min',32,'max',49)),
((SELECT id FROM facet_definition WHERE facet_code='SCREEN_INCH'),'S64','50~64인치',30,JSON_OBJECT('min',50,'max',64)),
((SELECT id FROM facet_definition WHERE facet_code='SCREEN_INCH'),'S74','65~74인치',40,JSON_OBJECT('min',65,'max',74)),
((SELECT id FROM facet_definition WHERE facet_code='SCREEN_INCH'),'S75P','75인치 이상',50,JSON_OBJECT('min',75,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'STAND','스탠드',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'WALL','벽걸이',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'SIDE_BY_SIDE','양문형',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'FOUR_DOOR','4도어',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'DRUM','드럼',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'TOP_LOAD','통돌이',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'CORDLESS','무선',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORM_FACTOR'),'CORDED','유선',80,NULL),
((SELECT id FROM facet_definition WHERE facet_code='POWER_W'),'PW100','100W 이하',10,JSON_OBJECT('min',0,'max',100)),
((SELECT id FROM facet_definition WHERE facet_code='POWER_W'),'PW500','100~500W',20,JSON_OBJECT('min',100,'max',500)),
((SELECT id FROM facet_definition WHERE facet_code='POWER_W'),'PW1000','500~1000W',30,JSON_OBJECT('min',500,'max',1000)),
((SELECT id FROM facet_definition WHERE facet_code='POWER_W'),'PW1000P','1000W 이상',40,JSON_OBJECT('min',1000,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='VOLTAGE'),'110','110V',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VOLTAGE'),'220','220V',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VOLTAGE'),'FREE','프리볼트',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE'),'128G','128GB',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE'),'256G','256GB',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE'),'512G','512GB',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE'),'1T','1TB',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE'),'2TP','2TB 이상',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='OS'),'WINDOWS','Windows',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='OS'),'MACOS','macOS',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='OS'),'ANDROID','Android',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='OS'),'IOS','iOS',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='OS'),'CHROMEOS','ChromeOS',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONNECTIVITY'),'WIRELESS','무선',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONNECTIVITY'),'BLUETOOTH','블루투스',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONNECTIVITY'),'WIFI','Wi-Fi',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONNECTIVITY'),'USB_C','USB-C',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CONNECTIVITY'),'WIRED','유선',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INSTALL_FEE'),'FREE','설치비 없음',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INSTALL_FEE'),'PAID','설치비 별도',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='INSTALL_FEE'),'DELIVERY_ONLY','배송만',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CARRIER'),'SKT','SKT',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CARRIER'),'KT','KT',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CARRIER'),'LGU','LG U+',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CARRIER'),'UNLOCKED','자급제',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WARRANTY'),'Y1','1년',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WARRANTY'),'Y2','2년',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WARRANTY'),'Y3P','3년 이상',30,NULL),
-- 가구/인테리어
((SELECT id FROM facet_definition WHERE facet_code='SEATS'),'P1','1인용',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SEATS'),'P2','2인용',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SEATS'),'P3','3인용',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SEATS'),'P4P','4인용 이상',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WIDTH_CM'),'W800','800mm 이하',10,JSON_OBJECT('min',0,'max',800)),
((SELECT id FROM facet_definition WHERE facet_code='WIDTH_CM'),'W1200','800~1200mm',20,JSON_OBJECT('min',800,'max',1200)),
((SELECT id FROM facet_definition WHERE facet_code='WIDTH_CM'),'W1600','1200~1600mm',30,JSON_OBJECT('min',1200,'max',1600)),
((SELECT id FROM facet_definition WHERE facet_code='WIDTH_CM'),'W1600P','1600mm 이상',40,JSON_OBJECT('min',1600,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='ASSEMBLY'),'FINISHED','완제품',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ASSEMBLY'),'SEMI','반조립',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ASSEMBLY'),'DIY','DIY',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'MODERN','모던',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'NORDIC','북유럽',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'NATURAL','내추럴',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'VINTAGE','빈티지',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'CLASSIC','클래식',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STYLE'),'INDUSTRIAL','인더스트리얼',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SET_COMPOSITION'),'SINGLE','단품',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SET_COMPOSITION'),'SET2','2종 세트',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SET_COMPOSITION'),'FULL','풀세트',30,NULL),
-- 출산/육아
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'NEWBORN','신생아',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'M0_6','0~6개월',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'M6_12','6~12개월',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'Y1_2','1~2세',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'Y3_5','3~5세',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'Y6P','6세 이상',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='AGE_RANGE'),'MOM','임산부',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BABY_GENDER'),'BOY','남아',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BABY_GENDER'),'GIRL','여아',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BABY_GENDER'),'UNISEX','공용',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'NB','신생아',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'S','S',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'M','M',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'L','L',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'XL','XL',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_STAGE'),'XXL','XXL',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_TYPE'),'BAND','밴드형',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DIAPER_TYPE'),'PANTS','팬티형',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORMULA_STAGE'),'S1','1단계',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORMULA_STAGE'),'S2','2단계',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORMULA_STAGE'),'S3','3단계',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FORMULA_STAGE'),'S4','4단계',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_LIMIT'),'K9','9kg 이하',10,JSON_OBJECT('min',0,'max',9)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_LIMIT'),'K18','9~18kg',20,JSON_OBJECT('min',9,'max',18)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_LIMIT'),'K36','18~36kg',30,JSON_OBJECT('min',18,'max',36)),
((SELECT id FROM facet_definition WHERE facet_code='SAFETY_MARK'),'Y','안전표시 있음',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ECO_CERT'),'ORGANIC','오가닉',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ECO_CERT'),'NO_FLUORESCENT','무형광',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ECO_CERT'),'NO_FRAGRANCE','무향',30,NULL),
-- 식품
((SELECT id FROM facet_definition WHERE facet_code='STORAGE_TEMP'),'ROOM','실온',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE_TEMP'),'COLD','냉장',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='STORAGE_TEMP'),'FROZEN','냉동',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_RANGE'),'G500','500g 이하',10,JSON_OBJECT('min',0,'max',500)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_RANGE'),'G1000','500g~1kg',20,JSON_OBJECT('min',500,'max',1000)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_RANGE'),'G3000','1~3kg',30,JSON_OBJECT('min',1000,'max',3000)),
((SELECT id FROM facet_definition WHERE facet_code='WEIGHT_RANGE'),'G3000P','3kg 이상',40,JSON_OBJECT('min',3000,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'IMMUNE','면역',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'GUT','장건강',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'BLOOD','혈행',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'EYE','눈',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'JOINT','관절',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'LIVER','간',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'FATIGUE','피로회복',70,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEALTH_FUNC'),'BODYFAT','체지방',80,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HFF_CERT'),'Y','건강기능식품',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FOOD_CERT'),'HACCP','HACCP',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FOOD_CERT'),'ORGANIC','유기농',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FOOD_CERT'),'NO_PESTICIDE','무농약',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FOOD_CERT'),'ECO','친환경',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FOOD_CERT'),'GAP','GAP',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ALLERGY_FREE'),'GLUTEN','글루텐 프리',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ALLERGY_FREE'),'MILK','우유 무첨가',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='ALLERGY_FREE'),'NUT','견과류 무첨가',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='NUTRITION'),'LOW_SUGAR','저당',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='NUTRITION'),'LOW_SALT','저염',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='NUTRITION'),'LOW_CAL','저칼로리',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='NUTRITION'),'HIGH_PROTEIN','고단백',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='NUTRITION'),'FIBER','식이섬유',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FLAVOR'),'ORIGINAL','오리지널',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FLAVOR'),'SPICY','매운맛',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FLAVOR'),'SWEET','단맛',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='FLAVOR'),'MILD','담백',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='COOK_TYPE'),'INSTANT','즉석·간편',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='COOK_TYPE'),'MEALKIT','밀키트',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='COOK_TYPE'),'RAW','원물',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='COOK_TYPE'),'NEEDS_COOK','조리 필요',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GMO'),'NON_GMO','Non-GMO',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='EXPIRY_SOON'),'SOON','임박 특가',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='EXPIRY_SOON'),'FRESH','30일 이상 남음',20,NULL),
-- 스포츠/레저
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'WEAR','의류',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'SHOES','신발',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'EQUIPMENT','장비',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'SUPPLY','용품·소품',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'PROTECTION','보호구',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='GEAR_TYPE'),'ACCESSORY','액세서리',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKILL_LEVEL'),'BEGINNER','입문',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKILL_LEVEL'),'INTERMEDIATE','중급',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='SKILL_LEVEL'),'ADVANCED','상급',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_ENV'),'INDOOR','실내',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_ENV'),'OUTDOOR','실외',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_ENV'),'BOTH','겸용',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CAPACITY_PERSON'),'C1','1인',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CAPACITY_PERSON'),'C2_3','2~3인',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CAPACITY_PERSON'),'C4_5','4~5인',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='CAPACITY_PERSON'),'C6P','6인 이상',40,NULL),
-- 여가/생활편의
((SELECT id FROM facet_definition WHERE facet_code='REGION'),'DOMESTIC','국내',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='REGION'),'OVERSEAS','해외',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'ONCE','1회',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'D1','1일',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'W1','1주',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'M1','1개월',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'M3','3개월',50,NULL),
((SELECT id FROM facet_definition WHERE facet_code='DURATION'),'M6P','6개월 이상',60,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_METHOD'),'VISIT','방문',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_METHOD'),'ONLINE','온라인·비대면',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_METHOD'),'DISPATCH','출장',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='USE_METHOD'),'MOBILE_COUPON','모바일쿠폰',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEADCOUNT'),'H1','1인',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEADCOUNT'),'H2','2인',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEADCOUNT'),'H3_4','3~4인',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='HEADCOUNT'),'GROUP','단체',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VALID_UNTIL'),'V30','30일',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VALID_UNTIL'),'V60','60일',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VALID_UNTIL'),'V90','90일',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='VALID_UNTIL'),'V365','1년',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='REFUND'),'FULL','전액 환불 가능',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='REFUND'),'PARTIAL','부분 환불',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='REFUND'),'NONE','환불 불가',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='RESERVE'),'REQUIRED','예약 필수',10,NULL),
-- 도서
((SELECT id FROM facet_definition WHERE facet_code='PUBLISH_YEAR'),'Y1','최근 1년',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PUBLISH_YEAR'),'Y3','최근 3년',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PUBLISH_YEAR'),'Y5','최근 5년',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PUBLISH_YEAR'),'OLD','그 이전',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_FORM'),'SINGLE','단행본',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_FORM'),'SET','세트·전집',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_FORM'),'MAGAZINE','잡지',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_FORM'),'POCKET','문고본',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_CONDITION'),'NEW','새 책',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_CONDITION'),'USED','중고',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LANGUAGE'),'KO','국내도서',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LANGUAGE'),'EN','영어',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LANGUAGE'),'JA','일본어',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='LANGUAGE'),'ZH','중국어',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='TARGET_AGE'),'INFANT','유아',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='TARGET_AGE'),'CHILD','어린이',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='TARGET_AGE'),'TEEN','청소년',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='TARGET_AGE'),'ADULT','성인',40,NULL),
((SELECT id FROM facet_definition WHERE facet_code='PAGES'),'P200','200쪽 이하',10,JSON_OBJECT('min',0,'max',200)),
((SELECT id FROM facet_definition WHERE facet_code='PAGES'),'P400','200~400쪽',20,JSON_OBJECT('min',200,'max',400)),
((SELECT id FROM facet_definition WHERE facet_code='PAGES'),'P600','400~600쪽',30,JSON_OBJECT('min',400,'max',600)),
((SELECT id FROM facet_definition WHERE facet_code='PAGES'),'P600P','600쪽 이상',40,JSON_OBJECT('min',600,'max',NULL)),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_SIZE'),'POCKET','문고판',10,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_SIZE'),'A5','A5',20,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_SIZE'),'B5','B5',30,NULL),
((SELECT id FROM facet_definition WHERE facet_code='BOOK_SIZE'),'LARGE','대형',40,NULL)
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), display_order = VALUES(display_order), meta_json = VALUES(meta_json);
